# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_five:
    has_velocity_limits: true
    max_velocity: 1102
    has_acceleration_limits: false
    max_acceleration: 0
  joint_four:
    has_velocity_limits: true
    max_velocity: 551
    has_acceleration_limits: false
    max_acceleration: 0
  joint_one:
    has_velocity_limits: true
    max_velocity: 210
    has_acceleration_limits: false
    max_acceleration: 0
  joint_three:
    has_velocity_limits: true
    max_velocity: 210
    has_acceleration_limits: false
    max_acceleration: 0
  joint_two:
    has_velocity_limits: true
    max_velocity: 210
    has_acceleration_limits: false
    max_acceleration: 0