# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: catalyst_arm
  joint_model_group_pose: up_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_one
    - joint_two
    - joint_three
    - joint_four
    - joint_five
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []

catalyst_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_one
    - joint_two
    - joint_three
    - joint_four
    - joint_five
  gains:
    joint_one:
      p: 50
      d: 0
      i: 10
      i_clamp: 5
    joint_two:
      p: 50
      d: 0
      i: 10
      i_clamp: 5
    joint_three:
      p: 50
      d: 0
      i: 10
      i_clamp: 5
    joint_four:
      p: 50
      d: 0
      i: 10
      i_clamp: 5
    joint_five:
      p: 50
      d: 0
      i: 10
      i_clamp: 5

